on: [push, pull_request]
name: every commit
jobs:

  build:
    env:
      # for private repo access
      GOPRIVATE: github.com/initia-labs/initiavm
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      # for private repo access
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: Build
        run: make build

  test:
    env:
      # for private repo access
      GOPRIVATE: github.com/initia-labs/initiavm
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install openssl
        run: sudo apt-get install libssl1.1 libssl-dev
      - name: Checkout code
        uses: actions/checkout@v3
      # for private repo access
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: Test
        run: make docs
        run: go test ./...